### ISSUE TITLE
Some improvements before moving to AliceO2

### ISSUE THREAD

**Issue by awegrzyn** [vladimirkosmala/TObejct2JSON#1]
- [x] Update documentation (it should work for both CC7 and MacOS)
- [x] Use two level of namespaces: `o2` and `quality_control`
- [x] Use `.h` instead of `.hpp`
- [x] Use namespaces in protectors `TOBJECT2JSON_HPP` -> `QUALITYCONTROL_TOBJECT2JSON_H`
- [x] Add copyright statement to each `.h` and `.cxx` file (see https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/src/BoostOptionsRetriever.cxx)
- [x] prefix member variables with 'm', eg: `sqlClient` -> `mSqlClient`
- [x] Fully document each member function and variable using Doxygen, (see: https://github.com/AliceO2Group/QualityControl/blob/master/Framework/include/QualityControl/CheckInterface.h)
- [x] `numberOfContextThread` should be configurable, eg: `TObject2JSON::startZmqServer(string endpoint, unsigned short int numberOfContextThread)`
- [x] `main.cpp`: Do not use string literals, either parse command line arguments or use Configuration library (https://github.com/AliceO2Group/Configuration)
- [x] JSON -> Json
- [x] Instead of `cout` use InfoLogger library

**Comment by vladimirkosmala** [comment]
- [ ] hiuhiuh

**Comment by vladimirkosmala** [comment]
Done for `Json` but strange, as ROOT uses `JSON`. The code will not be homogeneous.

**Comment by awegrzyn** [comment]
I'm just following O2 conventions

**Comment by vladimirkosmala** [comment]
#2 done in this PR
